/* The festival's own footage, hosted on Mux.
 *
 * Only the playback ID lives here. It is a public identifier, not a secret — the API token
 * that put these on the account is in `.env.local` and is needed to upload, never to play.
 * The masters are in `video-source/`, which is gitignored: Mux is a delivery layer, not an
 * archive. Re-run `npm run mux:upload` after adding a clip and paste the new ID in.
 *
 * Every clip is 9:16 — shot vertical, delivered vertical, framed vertical. Nothing here is
 * cropped to fit a landscape box.
 */

export interface Clip {
  readonly id: string;
  /** Mux playback ID. Streams at https://stream.mux.com/{playbackId}.m3u8 */
  readonly playbackId: string;
  /** Spoken caption, and the accessible name of the button that starts it. */
  readonly caption: string;
  /** Whole seconds, for the mono meta line. Mux's own duration, rounded. */
  readonly seconds: number;
  /**
   * Which second Mux cuts the poster from. Left off, Mux picks the frame itself, and its
   * choice is not always the one that sells the clip — a talking head mid-sentence, or a
   * fade. Chosen against a contact sheet of the master, per clip.
   */
  readonly posterTime?: number;
}

/**
 * The film at the top of Home. One frame, one caption, click to play — it does not autoplay
 * and it does not loop behind the copy. Motion is response, not ambience.
 */
export const FILM: Clip = {
  id: "the-film",
  playbackId: "gKf8B5gg5LGp4pMaFOpxBtoDF013EIlBhFmzJBfNVtL00",
  caption: "The film",
  seconds: 113,
  /* The aerial over the palms and the water. Chosen by the festival: it reads as the island
     rather than as one plate, and its mid-tones leave the play mark legible dead centre. */
  posterTime: 73,
};

/**
 * Last year's clips, in the order the strip reads them. The captions name the venue or the
 * night each was shot at — Wild, Alma and Bravo are three of the festival's host venues.
 * They are derived from the festival's own file names and are still to be confirmed; see
 * `project-docs/phase-1-deviations.md`.
 *
 * The design of record draws three. Six exist, and the strip was always built to scroll, so
 * all six ship — the padding maths in `LastYear` centre the first at scroll 0 either way.
 */
export const LAST_YEAR: readonly Clip[] = [
  {
    id: "opening-wild",
    playbackId: "VLTBdzWBIA9Wpxt1jff9PCBN2Sr6AQyBaiHtslUKJJM",
    caption: "Opening night at Wild",
    seconds: 69,
    /* The wine pour — the only frame in the whole set that says wine. */
    posterTime: 8.3,
  },
  {
    id: "alma",
    playbackId: "1YhT01jWuknJ4Hbzrp3UD42UUU02102h9yjt8YI02APBjPw",
    caption: "The gathering at Alma",
    seconds: 20,
    /* The kitchen line plating: hosted by the people cooking, in one image. */
    posterTime: 16.9,
  },
  {
    id: "bravo",
    playbackId: "Wpl13Md9umYLohhsyxBQp4UHFkARmRL8MYo5VLp2qmo",
    caption: "Restaurant Bravo",
    seconds: 19,
    /* The bartender mid-shake. The clip opens on black, so an early frame is a dead poster. */
    posterTime: 7.1,
  },
  {
    id: "day-one",
    playbackId: "7nP3o1kEOMVB028tZ01Go85XQ2EoYJmOtzC1JhSfyhvzI",
    caption: "Day one",
    seconds: 10,
    /* The tuna being broken down. Local, and the most arresting frame on the strip. */
    posterTime: 3.5,
  },
  {
    id: "fashion-show",
    playbackId: "Ptr487NY02UWag00DPQjmMcQxgsTl5VK1gLWLoLWoJ00zA",
    caption: "The fashion show",
    seconds: 6,
    /* Three models together; the clip opens on a black split-frame. */
    posterTime: 5.5,
  },
  {
    id: "final-night",
    playbackId: "2skA2C5h00uqmNKOVWdLmD02f006VrT00Ktgx00kS5ebBFW4",
    caption: "The final night",
    seconds: 31,
    /* Beach, beer, dusk — the final night as a place rather than a portrait. */
    posterTime: 11.6,
  },
];

export const LAST_YEAR_EYEBROW = "RELIVE LAST YEAR'S BEST MOMENTS";

/** The HLS ladder. Mux builds four rungs from 270x480 up to 1080x1920. */
export const streamUrl = (playbackId: string): string =>
  `https://stream.mux.com/${playbackId}.m3u8`;

/**
 * The poster frame, generated by Mux and free on every plan — so no still has to be cut by
 * hand, stored in `public/`, or kept in step when a clip is replaced. Width is the rendered
 * frame at 2x.
 */
export const posterUrl = (clip: Clip, width: number): string => {
  const at = clip.posterTime === undefined ? "" : `&time=${clip.posterTime}`;
  return `https://image.mux.com/${clip.playbackId}/thumbnail.webp?width=${width}&fit_mode=preserve${at}`;
};
